### ISSUE TITLE
Restore not working in mariadb

### ISSUE THREAD

**Issue by arulrajnet** [tamil-wiki/mediawiki-backup-restore#4]
The variable "SQL_REQUIRE_PRIMARY_KEY" not supported error came while restore in mariadb. 

https://github.com/tamil-wiki/mediawiki-backup-restore/blob/main/restore.sh#L64

**Comment by vijayabharathib** [comment]
Got another error while restoring mysql dump in test server with mariadb. 

ERROR 1273 (HY000) at line 2008: Unknown collation: 'utf8mb4_0900_ai_ci'

changing these two helped.
sed -i 's/utf8mb4_0900_ai_ci/utf8_general_ci/g' restore/dump.sql
sed -i 's/CHARSET=utf8mb4/CHARSET=utf8/g' restore/dump.sql
