### ISSUE TITLE
Collation error on restore

### ISSUE THREAD

**Issue by arulrajnet** [tamil-wiki/mediawiki-backup-restore#7]
While restoring from `10.8.4-MariaDB-log` (managed by digital ocean) to  `10.7.1-MariaDB-1:10.7.1+maria~focal`

Got the following error

```
ERROR 1253 (42000) at line 2494: COLLATION 'utf8mb4_unicode_ci' is not valid for CHARACTER SET 'utf8mb3'
```

To view the version of DB server

```
show variables where Variable_name in ('version','version_comment');
```

Similar issue #5

**Comment by ithiru** [comment]
Managed DB has different default collation, current in-house VM based mysql using utf8mb4_unicode_ci as default collation..
