### ISSUE TITLE
Backup - Daily, Weekly, Monthly and Yearly...

### ISSUE THREAD

**Issue by ithiru** [tamil-wiki/mediawiki-backup-restore#9]
- Script - Runs every hour - Run mysqldump to create file with date and hour to /daily folder - This can be incremental backup using mariadb backup command, otherwise this could could be too intensive and disrupting.. (https://mariadb.com/kb/en/incremental-backup-and-restore-with-mariabackup/)
- Script - Runs on Sunday - weekly - copy Sunday file to /weekly folder and remove files older than a year
- Script - Runs on 1st of Month - monthly - Copy 1st day of the month file to /monthly folder and remove files older than year

something like this - https://github.com/Kraymer/cronicle, https://serverfault.com/a/755793, https://serverfault.com/questions/575163/how-to-keep-daily-backups-for-a-week-weekly-for-a-month-monthly-for-a-year-a

https://tonyteaches.tech/rsync-backup-tutorial/
https://mariadb.com/kb/en/mariadb-dumpmysqldump/

**Comment by vijayabharathib** [comment]
The lifecycle json output will be like below. I'll find a way to parameterise `prefix` and `days` 
```
{
  "Rules": [
    {
      "Expiration": {
        "Days": 1
      },
      "ID": "Delete older than 24 hours.",
      "Prefix": "wiki/testing/hourly",
      "Status": "Enabled"
    },
    {
      "Expiration": {
        "Days": 7
      },
      "ID": "Delete older than 7 days.",
      "Prefix": "wiki/testing/daily",
      "Status": "Enabled"
    },
   {
      "Expiration": {
        "Days": 365
      },
      "ID": "Delete older than 1 year.",
      "Prefix": "wiki/testing/weekly",
      "Status": "Enabled"
    },
   {
      "Expiration": {
        "Days": 365
      },
      "ID": "Delete older than 1 year.",
      "Prefix": "wiki/testing/montly",
      "Status": "Enabled"
    },
    {
      "AbortIncompleteMultipartUpload": {
        "DaysAfterInitiation": 1
      },
      "ID": "Remove uncompleted uploads.",
      "Prefix": "",
      "Status": "Enabled"
    }
  ]
}
```

**Comment by vijayabharathib** [comment]
There will be 4 folders for back up
* hourly (retained for 24 hours) 
* daily (retained for 7 days) - as it is today 
* weekly  (retained for 1 year - 54 backups ) 
* monthly  (retained for 1 year - 12 backups )

**Comment by vijayabharathib** [comment]
```
  echo "${CRON_TIME} bash /backup.sh 2>&1 >> /dev/stdout" > /tmp/crontab.conf
  crontab /tmp/crontab.conf
```

This part can be changed to include the 4 different frequency backups - with backup.sh taking a parameter to decide where to upload (daily/hourly etc) 

```
  echo "${CRON_TIME_HOURLY} bash /backup.sh hourly 2>&1 >> /dev/stdout" > /tmp/crontab.conf
  echo "${CRON_TIME_DAILY} bash /backup.sh daily 2>&1 >> /dev/stdout" >> /tmp/crontab.conf
  echo "${CRON_TIME_WEEKLY} bash /backup.sh weekly 2>&1 >> /dev/stdout" >> /tmp/crontab.conf
  echo "${CRON_TIME_MONTHLY} bash /backup.sh monthly 2>&1 >> /dev/stdout" >> /tmp/crontab.conf
  crontab /tmp/crontab.conf
```

**Comment by vijayabharathib** [comment]
CRON_TIME_HOURLY = 0 */1 * * *  (every 1 hour) 
CRON_TIME_DAILY = 0 */24 * * * (every 24 hours) 
CRON_TIME_WEEKLY = 0 3 * * SUN (3am on SUNDAY) 
CRON_TIME_MONTLY = 0 4 1 * * (4am on 1st of every month)
